### ISSUE TITLE
Agenda: CTS: All

### ISSUE THREAD

**Issue by Rabia2219** [civictechstructure/admin#1]
### Overview
This issue tracks the agenda for our daily meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens every Monday
- [ ] MERL review

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Name of Person]
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

### Previous Meetings (link to each comment with the date)
[2023-09-28](https://github.com/civictechstructure/admin/issues/1#issuecomment-1737679931)

**Comment by Rabia2219** [comment]
## 2023-09-28 Meeting Agenda

### Recurring Items
- [ ] Review MERL Center [Admin Agenda](https://github.com/MERLCenter/merl-center-admin/issues/4)

### Recurring items: Happens every Monday
- [ ] MERL review

### New Items
- [x] Set up new repo at CTS for accounting (private)
- [x] Check to see if the issues labeled as MERL Center in notes-private are duplicates in MERL Center-admin. If not
   - [x] Add appropriate labels: 
       - move to MC
       - duplicate (also paste duplicate issue number in comment)
- [ ] Move the following repos to Civic Tech Index
   - [ ] https://github.com/hackforla/brigade-project-index-statusboard
   - [ ] https://github.com/hackforla/brigade-project-index
- [ ] Delete https://github.com/hackforla/test-delete-me
- [ ] Review the following repositories and decide what to do
   - [ ] https://github.com/hackforla/merl-center-site-eval 
   - [ ] https://github.com/hackforla/meeting-automations
   - [ ] https://github.com/hackforla/github-api-test
   - [ ] https://github.com/hackforla/project-groups
- [ ] Archive 
    - [ ] https://github.com/hackforla/undebate and add note on where information is hosted now
    - [ ] https://github.com/hackforla/ndoch-2017

#### Create Issues
- [x] [Move HfLA issues to CTS GitHub](https://github.com/civictechstructure/admin/issues/3)
   - [x] Create transfer repository at github.com/hackforla
   - [x] Identify HfLA issues to move to CTS
   - [x] Transfer issues to transfer repository (L)
   - [x] Move transfer repository from HfLA to CTS
- [ ] Move notes-private issues to HfLA GitHub
   - [x] Create transfer repository at [github.com/bonniewolfe/transfertohfla](https://github.com/bonniewolfe/transfertohfla/)
   - [ ] Identify note-private issues to move to HfLA
   - [ ] Transfer issues to transfer repository
   - [ ] Move transfer repository from notes-private to HfLA
- [ ] Move notes-private issues to CTS GitHub
   - [ ] Create transfer repository at github.com/bonniewolfe/notes-private/
   - [ ] Identify note-private issues to move to CTS
   - [ ] Transfer issues to transfer repository
   - [ ] Move transfer repository from notes-private to CTS
- CTS: Accounting
   - [ ] https://github.com/bonniewolfe/notes-private/issues/94#issuecomment-1581311315 (follow up with CTS contractor)
- Project Set Up
   - [ ] Add column headers to project board
- [ ] Review DPGCM assets https://github.com/bonniewolfe/dpgcm-resources and decide what to do
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Rabia2219** [comment]
## 2023-10-04 Meeting Agenda

### Recurring Items
- [ ] Review MERL Center [Admin Agenda](https://github.com/MERLCenter/merl-center-admin/issues/4)

### Recurring items: Happens every Monday
- [ ] MERL review

### New Items
- [ ] Determine proper location for MERL Center content submission images

### Items Carried Forward
- [ ] Move the following repos to Civic Tech Index
   - [ ] https://github.com/hackforla/brigade-project-index-statusboard
   - [ ] https://github.com/hackforla/brigade-project-index
- [ ] Delete https://github.com/hackforla/test-delete-me
- [ ] Review the following repositories and decide what to do
   - [ ] https://github.com/hackforla/merl-center-site-eval 
   - [ ] https://github.com/hackforla/meeting-automations
   - [ ] https://github.com/hackforla/github-api-test
   - [ ] https://github.com/hackforla/project-groups
- [ ] Archive 
    - [ ] https://github.com/hackforla/undebate and add note on where information is hosted now
    - [ ] https://github.com/hackforla/ndoch-2017

#### Create Issues
- [x] [Move notes-private issues to HfLA GitHub](https://github.com/civictechstructure/admin/issues/10)
   - [x] Create transfer repository at [github.com/bonniewolfe/transfertohfla](https://github.com/bonniewolfe/transfertohfla/)
   - [x] Identify note-private issues to move to HfLA
   - [x] Transfer issues to transfer repository
   - [x] Move transfer repository from notes-private to HfLA
- [x] [Move notes-private issues to CTS GitHub](https://github.com/civictechstructure/admin/issues/16)
   - [x] Create transfer repository at github.com/bonniewolfe/notes-private/
   - [x] Identify note-private issues to move to CTS
   - [x] Transfer issues to transfer repository
   - [x] Move transfer repository from notes-private to CTS
- CTS: Accounting
   - [ ] https://github.com/bonniewolfe/notes-private/issues/94#issuecomment-1581311315 (follow up with CTS contractor)
- Project Set Up
   - [ ] Add column headers to project board
- [ ] Review DPGCM assets https://github.com/bonniewolfe/dpgcm-resources and decide what to do
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Rabia2219** [comment]
#### 2023-10-27
- [x] Invoicing
- [x] Check on Cathy for Slack transition

**Comment by Rabia2219** [comment]
#### 2023-12-19
- [ ] Items to review later
   - [ ] https://techtogether.io/workshops
   - [ ] https://directory.civictech.guide/
   - [ ] https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-your-personal-account/merging-multiple-personal-accounts
